# -*- coding: utf-8 -*-
"""rec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RJZbHd-SnGNnP18Q4ky5lpcQYDDVLyxY
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import cosine_similarity
import joblib

st.set_page_config(layout="wide")
st.title("Fashion MNIST Image Recommendation System")

# Load precomputed embeddings and data
@st.cache_resource
def load_data():
    embeddings = joblib.load("image_embeddings.pkl")
    x_test = joblib.load("x_test_images.pkl")
    y_test = joblib.load("y_test_labels.pkl")
    similarity = cosine_similarity(embeddings.astype("float32"))
    return embeddings, x_test, y_test, similarity

embeddings, x_test, y_test, similarity_matrix = load_data()

# Sidebar for input
query_index = st.sidebar.slider("Select query image index", 0, len(x_test) - 1, 0)
top_n = st.sidebar.slider("Number of recommendations", 1, 10, 5)

# Display query image
st.subheader("Query Image")
st.image(x_test[query_index].reshape(28, 28), width=150, caption=f"Label: {y_test[query_index]}")

# Get top-N recommendations
similar_indices = similarity_matrix[query_index].argsort()[::-1][1:top_n + 1]

# Display recommendations
st.subheader(f"Top {top_n} Recommendations")
cols = st.columns(top_n)
for i, idx in enumerate(similar_indices):
    with cols[i]:
        st.image(x_test[idx].reshape(28, 28), width=100, caption=f"Label: {y_test[idx]}")